language: cpp
env:
###############################################################################
  # Must manually specifiy Python path otherwise we pick up TravisCI's install in /opt
  # which does not have our yaml and jsonschema modules :(
  - C_COMPILER=gcc CXX_COMPILER=g++ ARCH=x86_64 CONFIGURE_ONLY=0 PYTHON_EXECUTABLE=/usr/bin/python2
  - C_COMPILER=gcc CXX_COMPILER=g++ ARCH=i686 CONFIGURE_ONLY=0 PYTHON_EXECUTABLE=/usr/bin/python2
  # FIXME: Need to find a way to install LLVM's OpenMP library so Clang can build OpenMP benchmarks
  - C_COMPILER=clang-3.7 CXX_COMPILER=clang++-3.7 ARCH=x86_64 CONFIGURE_ONLY=0 PYTHON_EXECUTABLE=/usr/bin/python2
  - C_COMPILER=clang-3.7 CXX_COMPILER=clang++-3.7 ARCH=i686 CONFIGURE_ONLY=0 PYTHON_EXECUTABLE=/usr/bin/python2
  # Try different python versions without building
  - C_COMPILER=gcc CXX_COMPILER=g++ ARCH=i686 CONFIGURE_ONLY=1 PYTHON_EXECUTABLE=/usr/bin/python2
  - C_COMPILER=gcc CXX_COMPILER=g++ ARCH=i686 CONFIGURE_ONLY=1 PYTHON_EXECUTABLE=/usr/bin/python3
###############################################################################
# Use TravisCI legacy infrastructure so we can install the packages we need, the apt add-ons
# doesn't work with Ubuntu 14.04 (Trusty)
sudo: required
dist: trusty
before_install:
  - sudo echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main"
  - sudo sh -c 'echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main" >> /etc/apt/sources.list.d/llvm.list'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get install -y g++-multilib gcc-multilib libc6-dev-i386 clang-3.7 doxygen libyaml-dev python-pip python3-pip python python3
  - sudo pip2 install jsonschema pyyaml
  - sudo pip3 install jsonschema pyyaml
script:
  - scripts/travisci-build.sh
