language: cpp
env:
###############################################################################
  # Must manually specifiy Python path otherwise we pick up TravisCI's install in /opt
  # which does not have our yaml and jsonschema modules :(
  - C_COMPILER=gcc CXX_COMPILER=g++ PYTHON_EXECUTABLE=/usr/bin/python2
  - C_COMPILER=gcc CXX_COMPILER=g++ PYTHON_EXECUTABLE=/usr/bin/python3
  - C_COMPILER=clang-3.4 CXX_COMPILER=clang++-3.4 PYTHON_EXECUTABLE=/usr/bin/python2
  - C_COMPILER=clang-3.4 CXX_COMPILER=clang++-3.4 PYTHON_EXECUTABLE=/usr/bin/python3
###############################################################################
# Use TravisCI legacy infrastructure so we can install the packages we need.
sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y g++ gcc libc6-dev clang-3.4 doxygen libyaml-dev python-pip python3-pip python python3
  - sudo pip2 install jsonschema pyyaml
  - sudo pip3 install jsonschema pyyaml
  # Build script expects clang-3.4 to be the binary name in the path
  - sudo ln -s /usr/bin/clang /usr/bin/clang-3.4
  - sudo ln -s /usr/bin/clang++ /usr/bin/clang++-3.4
script:
  - scripts/travisci-build.sh
